[package]
name = "tokenizer_text"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
regex = "1.9"
tiktoken-rs = "0.6.0"
tch = "0.20.0"
